import json
import logging
import re
from datetime import datetime

from fastapi import HTTPException
from openai import AsyncOpenAI
from sqlalchemy.orm import Session

from backend.app.core.config import settings

from backend.app.models.resume.resume import Resume
from backend.app.models.recruiter.recruiter import RecruiterViewAnalysis

from backend.app.prompts.recruiter.recruiter_view_prompts import (
    RECRUITER_VIEW_SYSTEM_PROMPT,
    build_recruiter_view_prompt,
)

from backend.app.schemas.recruiter.recruiter_view import (
    RecruiterViewRequest,
    RecruiterViewResponse,
    RecruiterSignal,
    RecruiterFeedbackCard,
)

from backend.app.services.privacy.llm_privacy import prepare_data

client = AsyncOpenAI(
    api_key=settings.OPENAI_API_KEY,
)

logger = logging.getLogger(__name__)


def _serialize_recruiter_view_analysis(
    response: RecruiterViewResponse,
) -> dict:
    """
    Convert the validated recruiter analysis response
    into a JSON-safe dictionary for database storage.
    """
    return response.model_dump()


def _safe_json_dict(value) -> dict:
    """
    Convert a stored JSON / JSONB value into a dictionary.
    Some database drivers may return JSONB as dict, others as string.
    """
    if isinstance(value, dict):
        return value

    if isinstance(value, str):
        try:
            parsed = json.loads(value)
        except Exception:
            return {}

        if isinstance(parsed, dict):
            return parsed

    return {}


def _get_resume_analysis_context(
    *,
    db: Session | None,
    user_id: int | None,
    resume_id: int | None,
) -> dict:
    """
    Load the latest saved resume analysis so Recruiter View
    can reuse structured resume data generated by Resume Builder.
    """
    if not db or not user_id or not resume_id:
        return {}

    resume = (
        db.query(Resume)
        .filter(
            Resume.id == resume_id,
            Resume.user_id == user_id,
        )
        .first()
    )

    if not resume:
        return {}

    latest_analysis = _safe_json_dict(
        resume.latest_resume_analysis,
    )

    structured_resume_data = _safe_json_dict(
        latest_analysis.get("structured_resume_data"),
    )

    return {
        "latest_ats_score": resume.latest_ats_score,
        "latest_analysis": latest_analysis,
        "structured_resume_data": structured_resume_data,
    }


def _build_recruiter_resume_context(
    *,
    resume_content: str,
    resume_analysis_context: dict,
) -> str:
    """
    Enrich the raw resume text with saved structured resume analysis.
    This gives Recruiter View access to extracted skills, projects,
    seniority and ATS/recruiter findings without changing the API shape.
    """
    structured_resume_data = resume_analysis_context.get(
        "structured_resume_data",
        {},
    )

    latest_analysis = resume_analysis_context.get(
        "latest_analysis",
        {},
    )

    if not structured_resume_data and not latest_analysis:
        return resume_content

    return f"""
Resume Content:
{resume_content}

Saved Resume Analysis Context:
{json.dumps(resume_analysis_context, ensure_ascii=False)}
""".strip()


def calculate_recruiter_signals(
    resume_content: str,
) -> RecruiterSignal:
    """
    Calculate local recruiter-oriented resume signals
    such as readability, technical depth and impact density.
    """
    text = (resume_content or "").lower()

    readability = 70
    impact_density = 50
    technical_depth = 50
    visual_hierarchy = 70

    avg_sentence_length = (
        len(text.split()) /
        max(1, len(text.split(".")))
    )

    if avg_sentence_length < 25:
        readability += 15

    if "\n" in text:
        readability += 6

    number_matches = len(
        re.findall(r"\d+", text)
    )

    impact_density += min(
        35,
        number_matches * 4,
    )

    keyword_count = len(
        re.findall(
            r"\b(api|python|excel|sales|marketing|figma|analytics|management|react|finance|fastapi|sql|postgres|typescript|ai|rag|llm)\b",
            text,
        )
    )

    technical_depth += min(
        35,
        keyword_count * 4,
    )

    if "-" in text or "•" in text:
        visual_hierarchy += 10

    if len(text.splitlines()) > 10:
        visual_hierarchy += 10

    return RecruiterSignal(
        readability=max(0, min(100, readability)),
        impact_density=max(0, min(100, impact_density)),
        technical_depth=max(0, min(100, technical_depth)),
        visual_hierarchy=max(0, min(100, visual_hierarchy)),
    )


def save_recruiter_view_analysis(
    *,
    db: Session,
    user_id: int,
    resume_id: int,
    analysis: RecruiterViewResponse,
) -> RecruiterViewAnalysis:
    """
    Save or update the recruiter view analysis
    for the selected user-owned resume.
    """
    resume = (
        db.query(Resume)
        .filter(
            Resume.id == resume_id,
            Resume.user_id == user_id,
        )
        .first()
    )

    if not resume:
        raise HTTPException(
            status_code=404,
            detail="Resume not found",
        )

    existing_analysis = (
        db.query(RecruiterViewAnalysis)
        .filter(
            RecruiterViewAnalysis.user_id == user_id,
            RecruiterViewAnalysis.resume_id == resume_id,
        )
        .first()
    )

    if not existing_analysis:
        existing_analysis = RecruiterViewAnalysis(
            user_id=user_id,
            resume_id=resume_id,
        )
        db.add(existing_analysis)

    existing_analysis.recruiter_score = analysis.recruiter_score
    existing_analysis.analysis = _serialize_recruiter_view_analysis(
        analysis,
    )
    existing_analysis.analyzed_at = datetime.utcnow()

    db.commit()
    db.refresh(existing_analysis)

    return existing_analysis


def get_saved_recruiter_view_analysis(
    *,
    db: Session,
    user_id: int,
    resume_id: int,
) -> RecruiterViewAnalysis | None:
    """
    Return the previously saved recruiter analysis
    for the selected resume if it exists.
    """
    return (
        db.query(RecruiterViewAnalysis)
        .filter(
            RecruiterViewAnalysis.user_id == user_id,
            RecruiterViewAnalysis.resume_id == resume_id,
        )
        .first()
    )


async def analyze_recruiter_view(
    payload: RecruiterViewRequest,
    db: Session | None = None,
    user_id: int | None = None,
) -> RecruiterViewResponse:
    """
    Run an AI-powered recruiter perspective analysis,
    calculate local recruiter signals and optionally
    persist the analysis result.
    """
    clean_resume_content = prepare_data(payload.resume_content)
    clean_target_role = prepare_data(payload.target_role or "")

    resume_analysis_context = _get_resume_analysis_context(
        db=db,
        user_id=user_id,
        resume_id=payload.resume_id,
    )

    recruiter_resume_context = _build_recruiter_resume_context(
        resume_content=clean_resume_content,
        resume_analysis_context=resume_analysis_context,
    )

    prompt = build_recruiter_view_prompt(
        language=payload.language,
        resume_content=recruiter_resume_context,
        target_role=clean_target_role,
    )

    try:
        response = await client.chat.completions.create(
            model="gpt-4o-mini",
            temperature=0.4,
            response_format={
                "type": "json_object",
            },
            messages=[
                {
                    "role": "system",
                    "content": RECRUITER_VIEW_SYSTEM_PROMPT,
                },
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
        )
    except Exception as exc:
        logger.exception(
            "Recruiter view AI request failed for user_id=%s resume_id=%s target_role=%s",
            user_id,
            payload.resume_id,
            payload.target_role,
        )
        raise HTTPException(
            status_code=500,
            detail="Failed to analyze recruiter view",
        ) from exc

    content = response.choices[0].message.content

    try:
        parsed = json.loads(content)

        if not isinstance(parsed, dict):
            raise HTTPException(
                status_code=500,
                detail="Invalid recruiter analysis response structure",
            )

    except Exception as exc:
        logger.exception(
            "Recruiter view JSON parsing failed for user_id=%s resume_id=%s response_preview=%s",
            user_id,
            payload.resume_id,
            content[:500] if content else "",
        )
        raise HTTPException(
            status_code=500,
            detail="Invalid recruiter analysis response",
        ) from exc

    signals = calculate_recruiter_signals(
        clean_resume_content,
    )

    recruiter_score = int(
        (
            signals.readability +
            signals.impact_density +
            signals.technical_depth +
            signals.visual_hierarchy
        ) / 4
    )

    analysis = RecruiterViewResponse(
        recruiter_score=recruiter_score,
        signals=signals,
        strengths=parsed.get("strengths", [])[:4],
        weak_spots=parsed.get("weak_spots", [])[:4],
        missing_impact=parsed.get("missing_impact", [])[:4],
        ai_feedback=[
            RecruiterFeedbackCard(**item)
            for item in parsed.get("ai_feedback", [])[:3]
        ],
    )

    if payload.resume_id and db and user_id:
        try:
            save_recruiter_view_analysis(
                db=db,
                user_id=user_id,
                resume_id=payload.resume_id,
                analysis=analysis,
            )
        except HTTPException:
            raise
        except Exception as exc:
            logger.exception(
                "Failed to persist recruiter view analysis for user_id=%s resume_id=%s",
                user_id,
                payload.resume_id,
            )
            raise HTTPException(
                status_code=500,
                detail="Failed to save recruiter analysis",
            ) from exc

    return analysis
