/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResumeExportRouteImport } from './routes/resume-export'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecruiterViewRouteImport } from './routes/recruiter-view'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkedinRouteImport } from './routes/linkedin'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoverLettersRouteImport } from './routes/cover-letters'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CareerPathRouteImport } from './routes/career-path'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumesIndexRouteImport } from './routes/resumes.index'
import { Route as ResumesResumeIdRouteImport } from './routes/resumes.$resumeId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeExportRoute = ResumeExportRouteImport.update({
  id: '/resume-export',
  path: '/resume-export',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterViewRoute = RecruiterViewRouteImport.update({
  id: '/recruiter-view',
  path: '/recruiter-view',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinRoute = LinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLettersRoute = CoverLettersRouteImport.update({
  id: '/cover-letters',
  path: '/cover-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerPathRoute = CareerPathRouteImport.update({
  id: '/career-path',
  path: '/career-path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesIndexRoute = ResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesResumeIdRoute = ResumesResumeIdRouteImport.update({
  id: '/resumes/$resumeId',
  path: '/resumes/$resumeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/career-path': typeof CareerPathRoute
  '/coach': typeof CoachRoute
  '/cover-letters': typeof CoverLettersRoute
  '/dashboard': typeof DashboardRoute
  '/interview': typeof InterviewRoute
  '/linkedin': typeof LinkedinRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/recruiter-view': typeof RecruiterViewRoute
  '/register': typeof RegisterRoute
  '/resume-export': typeof ResumeExportRoute
  '/settings': typeof SettingsRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/resumes/': typeof ResumesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/career-path': typeof CareerPathRoute
  '/coach': typeof CoachRoute
  '/cover-letters': typeof CoverLettersRoute
  '/dashboard': typeof DashboardRoute
  '/interview': typeof InterviewRoute
  '/linkedin': typeof LinkedinRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/recruiter-view': typeof RecruiterViewRoute
  '/register': typeof RegisterRoute
  '/resume-export': typeof ResumeExportRoute
  '/settings': typeof SettingsRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/resumes': typeof ResumesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/career-path': typeof CareerPathRoute
  '/coach': typeof CoachRoute
  '/cover-letters': typeof CoverLettersRoute
  '/dashboard': typeof DashboardRoute
  '/interview': typeof InterviewRoute
  '/linkedin': typeof LinkedinRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/recruiter-view': typeof RecruiterViewRoute
  '/register': typeof RegisterRoute
  '/resume-export': typeof ResumeExportRoute
  '/settings': typeof SettingsRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/resumes/': typeof ResumesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/career-path'
    | '/coach'
    | '/cover-letters'
    | '/dashboard'
    | '/interview'
    | '/linkedin'
    | '/login'
    | '/portfolio'
    | '/recruiter-view'
    | '/register'
    | '/resume-export'
    | '/settings'
    | '/resumes/$resumeId'
    | '/resumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/career-path'
    | '/coach'
    | '/cover-letters'
    | '/dashboard'
    | '/interview'
    | '/linkedin'
    | '/login'
    | '/portfolio'
    | '/recruiter-view'
    | '/register'
    | '/resume-export'
    | '/settings'
    | '/resumes/$resumeId'
    | '/resumes'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/career-path'
    | '/coach'
    | '/cover-letters'
    | '/dashboard'
    | '/interview'
    | '/linkedin'
    | '/login'
    | '/portfolio'
    | '/recruiter-view'
    | '/register'
    | '/resume-export'
    | '/settings'
    | '/resumes/$resumeId'
    | '/resumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CareerPathRoute: typeof CareerPathRoute
  CoachRoute: typeof CoachRoute
  CoverLettersRoute: typeof CoverLettersRoute
  DashboardRoute: typeof DashboardRoute
  InterviewRoute: typeof InterviewRoute
  LinkedinRoute: typeof LinkedinRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
  RecruiterViewRoute: typeof RecruiterViewRoute
  RegisterRoute: typeof RegisterRoute
  ResumeExportRoute: typeof ResumeExportRoute
  SettingsRoute: typeof SettingsRoute
  ResumesResumeIdRoute: typeof ResumesResumeIdRoute
  ResumesIndexRoute: typeof ResumesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-export': {
      id: '/resume-export'
      path: '/resume-export'
      fullPath: '/resume-export'
      preLoaderRoute: typeof ResumeExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter-view': {
      id: '/recruiter-view'
      path: '/recruiter-view'
      fullPath: '/recruiter-view'
      preLoaderRoute: typeof RecruiterViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin': {
      id: '/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof LinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letters': {
      id: '/cover-letters'
      path: '/cover-letters'
      fullPath: '/cover-letters'
      preLoaderRoute: typeof CoverLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-path': {
      id: '/career-path'
      path: '/career-path'
      fullPath: '/career-path'
      preLoaderRoute: typeof CareerPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/': {
      id: '/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof ResumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$resumeId': {
      id: '/resumes/$resumeId'
      path: '/resumes/$resumeId'
      fullPath: '/resumes/$resumeId'
      preLoaderRoute: typeof ResumesResumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  CareerPathRoute: CareerPathRoute,
  CoachRoute: CoachRoute,
  CoverLettersRoute: CoverLettersRoute,
  DashboardRoute: DashboardRoute,
  InterviewRoute: InterviewRoute,
  LinkedinRoute: LinkedinRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
  RecruiterViewRoute: RecruiterViewRoute,
  RegisterRoute: RegisterRoute,
  ResumeExportRoute: ResumeExportRoute,
  SettingsRoute: SettingsRoute,
  ResumesResumeIdRoute: ResumesResumeIdRoute,
  ResumesIndexRoute: ResumesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
