/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as RecruiterViewRouteImport } from './routes/recruiter-view'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LinkedinRouteImport } from './routes/linkedin'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoverLettersRouteImport } from './routes/cover-letters'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CareerPathRouteImport } from './routes/career-path'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterViewRoute = RecruiterViewRouteImport.update({
  id: '/recruiter-view',
  path: '/recruiter-view',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinRoute = LinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLettersRoute = CoverLettersRouteImport.update({
  id: '/cover-letters',
  path: '/cover-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerPathRoute = CareerPathRouteImport.update({
  id: '/career-path',
  path: '/career-path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/career-path': typeof CareerPathRoute
  '/coach': typeof CoachRoute
  '/cover-letters': typeof CoverLettersRoute
  '/dashboard': typeof DashboardRoute
  '/interview': typeof InterviewRoute
  '/linkedin': typeof LinkedinRoute
  '/portfolio': typeof PortfolioRoute
  '/recruiter-view': typeof RecruiterViewRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/career-path': typeof CareerPathRoute
  '/coach': typeof CoachRoute
  '/cover-letters': typeof CoverLettersRoute
  '/dashboard': typeof DashboardRoute
  '/interview': typeof InterviewRoute
  '/linkedin': typeof LinkedinRoute
  '/portfolio': typeof PortfolioRoute
  '/recruiter-view': typeof RecruiterViewRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/career-path': typeof CareerPathRoute
  '/coach': typeof CoachRoute
  '/cover-letters': typeof CoverLettersRoute
  '/dashboard': typeof DashboardRoute
  '/interview': typeof InterviewRoute
  '/linkedin': typeof LinkedinRoute
  '/portfolio': typeof PortfolioRoute
  '/recruiter-view': typeof RecruiterViewRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/career-path'
    | '/coach'
    | '/cover-letters'
    | '/dashboard'
    | '/interview'
    | '/linkedin'
    | '/portfolio'
    | '/recruiter-view'
    | '/resume'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/career-path'
    | '/coach'
    | '/cover-letters'
    | '/dashboard'
    | '/interview'
    | '/linkedin'
    | '/portfolio'
    | '/recruiter-view'
    | '/resume'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/career-path'
    | '/coach'
    | '/cover-letters'
    | '/dashboard'
    | '/interview'
    | '/linkedin'
    | '/portfolio'
    | '/recruiter-view'
    | '/resume'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CareerPathRoute: typeof CareerPathRoute
  CoachRoute: typeof CoachRoute
  CoverLettersRoute: typeof CoverLettersRoute
  DashboardRoute: typeof DashboardRoute
  InterviewRoute: typeof InterviewRoute
  LinkedinRoute: typeof LinkedinRoute
  PortfolioRoute: typeof PortfolioRoute
  RecruiterViewRoute: typeof RecruiterViewRoute
  ResumeRoute: typeof ResumeRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter-view': {
      id: '/recruiter-view'
      path: '/recruiter-view'
      fullPath: '/recruiter-view'
      preLoaderRoute: typeof RecruiterViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin': {
      id: '/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof LinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letters': {
      id: '/cover-letters'
      path: '/cover-letters'
      fullPath: '/cover-letters'
      preLoaderRoute: typeof CoverLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-path': {
      id: '/career-path'
      path: '/career-path'
      fullPath: '/career-path'
      preLoaderRoute: typeof CareerPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  CareerPathRoute: CareerPathRoute,
  CoachRoute: CoachRoute,
  CoverLettersRoute: CoverLettersRoute,
  DashboardRoute: DashboardRoute,
  InterviewRoute: InterviewRoute,
  LinkedinRoute: LinkedinRoute,
  PortfolioRoute: PortfolioRoute,
  RecruiterViewRoute: RecruiterViewRoute,
  ResumeRoute: ResumeRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
